# Generated by Django 4.0.6 on 2022-11-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leaveModel',
            fields=[
                ('leaveId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30)),
                ('leaveDate', models.DateField()),
                ('leaveDiv', models.CharField(max_length=10)),
                ('leaveReason', models.CharField(max_length=50)),
                ('leaveStatus', models.BooleanField(default=False, verbose_name='Approved')),
            ],
        ),
    ]
