# Generated by Django 4.0.6 on 2022-11-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemodel',
            name='leaveRecords',
            field=models.FileField(default=1, upload_to='media/leave/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavemodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
