# Generated by Django 4.0.6 on 2022-09-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0002_remove_account_fname_remove_account_lname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
