# Generated by Django 4.0.6 on 2022-09-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0004_account_fname_account_lname_account_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sdetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=100, null=True)),
                ('lname', models.CharField(blank=True, max_length=100, null=True)),
                ('hname', models.CharField(blank=True, max_length=100, null=True)),
                ('father', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('pmobile', models.BigIntegerField(default=0)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('mobile', models.BigIntegerField(default=0)),
                ('dob', models.DateTimeField(auto_now_add=True)),
                ('caste', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('pschool', models.CharField(blank=True, max_length=100, null=True)),
                ('mark', models.IntegerField(blank=True, max_length=100, null=True)),
                ('Stream', models.CharField(blank=True, max_length=100, null=True)),
                ('slanguage', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('gname', models.CharField(blank=True, max_length=100, null=True)),
                ('gmobile', models.BigIntegerField(blank=True, max_length=100, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
            ],
        ),
    ]
