# Generated by Django 4.0.6 on 2022-09-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0005_sdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sdetails',
            name='username',
        ),
    ]
