# Generated by Django 4.0.6 on 2022-10-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0008_account_groups_account_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdetails',
            name='gmobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sdetails',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
