# Generated by Django 4.0.6 on 2022-10-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0009_alter_sdetails_gmobile_alter_sdetails_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdetails',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='sdetails',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='sdetails',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='sdetails',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='sdetails',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='sdetails',
            name='is_superadmin',
        ),
        migrations.RemoveField(
            model_name='sdetails',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='sdetails',
            name='last_login',
        ),
    ]
