# Generated by Django 4.0.6 on 2022-10-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0010_remove_sdetails_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdetails',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
