# Generated by Django 4.0.6 on 2022-10-10 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0011_alter_sdetails_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdetails',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='sdetails',
            name='nationality',
        ),
    ]
