# Generated by Django 4.0.6 on 2022-10-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0013_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_img',
            field=models.ImageField(null=True, upload_to='course/subject'),
        ),
    ]
