# Generated by Django 4.0.6 on 2022-10-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0016_sdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdetails',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
