# Generated by Django 4.0.6 on 2022-10-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0017_alter_sdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdetails',
            name='dob',
            field=models.DateTimeField(),
        ),
    ]
