# Generated by Django 4.0.6 on 2022-11-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0019_alter_account_date_joined_alter_account_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Student_email', models.EmailField(max_length=100, unique=True)),
                ('Student_mob', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commerce_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Student_email', models.EmailField(max_length=100, unique=True)),
                ('Student_mob', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HomeScience_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Student_email', models.EmailField(max_length=100, unique=True)),
                ('Student_mob', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Humanities_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Student_email', models.EmailField(max_length=100, unique=True)),
                ('Student_mob', models.BigIntegerField(default=0)),
            ],
        ),
    ]
