# Generated by Django 4.0.6 on 2022-11-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0021_alter_account_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdetails',
            name='dob',
            field=models.DateField(),
        ),
    ]
