# Generated by Django 4.0.6 on 2022-11-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0023_rename_homescience_class_class_biomaths_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdetails',
            name='gmobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sdetails',
            name='pmobile',
            field=models.IntegerField(default=0),
        ),
    ]
