# Generated by Django 4.0.6 on 2022-11-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0024_alter_sdetails_gmobile_alter_sdetails_pmobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdetails',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
