# Generated by Django 4.0.6 on 2022-11-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0026_alter_sdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdetails',
            name='gmobile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sdetails',
            name='pmobile',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
