# Generated by Django 4.0.6 on 2022-11-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0027_alter_sdetails_gmobile_alter_sdetails_pmobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdetails',
            name='mark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
