# Generated by Django 4.0.6 on 2022-11-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0028_alter_sdetails_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
