# Generated by Django 4.0.6 on 2022-11-20 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0030_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLanguage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SLanguage_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.course')),
            ],
        ),
    ]
