# Generated by Django 4.0.6 on 2022-11-20 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0032_subjects_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdetails',
            name='Stream',
        ),
        migrations.AddField(
            model_name='sdetails',
            name='Course_name',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.course'),
            preserve_default=False,
        ),
    ]
