# Generated by Django 4.0.6 on 2022-11-20 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0033_remove_sdetails_stream_sdetails_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdetails',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
