# Generated by Django 4.0.6 on 2022-11-20 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0034_alter_sdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='Course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_name', to='Schoolapp.course'),
        ),
    ]
