# Generated by Django 4.0.6 on 2022-11-20 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0035_alter_subjects_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='Course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.course'),
        ),
    ]
