# Generated by Django 4.0.6 on 2022-11-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0036_alter_subjects_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdetails',
            name='email',
            field=models.EmailField(blank=True, default=0, max_length=254, null=True),
        ),
    ]
