# Generated by Django 4.0.6 on 2022-11-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0037_alter_sdetails_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdetails',
            name='Course_name',
        ),
        migrations.AddField(
            model_name='sdetails',
            name='Stream',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
