# Generated by Django 4.0.6 on 2022-10-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_name_teacher_account_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_account',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='teacher_account',
            name='is_teacher',
            field=models.BooleanField(default=True),
        ),
    ]
