# Generated by Django 4.0.6 on 2022-10-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_teacher_account_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_account',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
