# Generated by Django 4.0.6 on 2022-10-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacher_account_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tdetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=100, null=True)),
                ('lname', models.CharField(blank=True, max_length=100, null=True)),
                ('hname', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('mobile', models.BigIntegerField(default=0)),
                ('dob', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher_account',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='teacher_account',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='teacher_account',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='teacher_account',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='teacher_account',
            name='place',
        ),
        migrations.RemoveField(
            model_name='teacher_account',
            name='qualification',
        ),
    ]
