# Generated by Django 4.0.6 on 2022-11-11 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_tdetails_remove_teacher_account_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher_Account',
            new_name='Teacher',
        ),
    ]
