# Generated by Django 4.0.6 on 2022-11-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_rename_teacher_account_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
