# Generated by Django 4.0.6 on 2022-11-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_alter_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdetails',
            name='caste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tdetails',
            name='resume',
            field=models.FileField(default=None, upload_to='resume/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tdetails',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tdetails',
            name='timage',
            field=models.FileField(default=None, upload_to='T_image/'),
            preserve_default=False,
        ),
    ]
