# Generated by Django 4.0.6 on 2022-11-20 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_tdetails_caste_tdetails_resume_tdetails_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdetails',
            name='email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
            preserve_default=False,
        ),
    ]
