# Generated by Django 4.0.6 on 2022-11-20 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0031_slanguage'),
        ('teacher', '0010_tdetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdetails',
            name='Course_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.course'),
            preserve_default=False,
        ),
    ]
