# Generated by Django 4.0.6 on 2022-11-20 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0031_slanguage'),
        ('teacher', '0011_tdetails_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdetails',
            name='Course_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.course'),
        ),
    ]
