# Generated by Django 4.0.6 on 2022-11-20 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0013_alter_tdetails_resume_alter_tdetails_timage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdetails',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
